name: PlatformIO CI

on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: [examples/absoluteXYZ.ino]

    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO
      run: pio ci --lib="." --board=nodemcuv2 --board=d1_mini
      env:
        PLATFORMIO_CI_SRC: ${{ matrix.example }}

    - uses: actions/checkout@v2

    - name: Fetch latest release version
      id: fetch-latest-release
      uses: reloc8/action-latest-release-version@1.0.0

    - name: Test
      run: echo ${{ steps.fetch-latest-release.outputs.latest-release }}
